# Hyprland window border colors — Chroma "frost"
general {
    col.active_border   = rgba(bac5d1cc) rgba(1e2229ff) 45deg
    col.inactive_border = rgba(1e2229aa)
}

group {
    col.border_active   = rgba(bac5d1cc)
    col.border_inactive = rgba(1e222966)
}
